### ISSUE TITLE
font-face-modern mixininde dosya yolunun dinamikleştirilmesi

### ISSUE THREAD

**Issue by hsnaydd** [atolye15/web-starter-kit#78]
```scss
@mixin font-face-modern(
  $font-name,
  $font-folder,
  $font-file-name,
  $font-weight: normal,
  $font-style: normal
) {
  @font-face {
    font-family: $font-name;
    font-style: $font-style;
    font-weight: $font-weight;
    src: url('#{$font-folder}/#{$font-file-name}.woff2') format('woff2'),
      url('#{$font-folder}/#{$font-file-name}.woff') format('woff'),
      url('#{$font-folder}/#{$font-file-name}.ttf') format('truetype'); // Chrome 4+, Firefox 3.5, Opera 10+, Safari 3—5 */
  }
}
```
